import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { HomePage } from '../../components/pages/fixed/home/HomePage'
import { readJson } from '../../lib/common/readJson'
import { HomeJson, defaultHomeJson, homeJsonPath } from '../../components/pages/fixed/home/homeJson'

const inter = Inter({ subsets: ['latin'] })

const Home = ({ homeJson }: { homeJson: HomeJson }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <HomePage
          homeJson={homeJson}
        />
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const homeJson = readJson<HomeJson>(homeJsonPath, defaultHomeJson);
  return {
    props: { homeJson }
  }
};

export default Home;